(define (run-length-encode elts)
  (define (int elt len l)
    (if (null? l)
        (if (= len 0)
            '()
            (list (list len elt)))
        (if (= elt (car l))
            (int elt (+ 1 len) (cdr l))
            (cons (list len elt) (int (car l) 1 (cdr l))))))
  (if (null? elts)
      '()
      (int (car elts) 1 (cdr elts))))
