(define (make-account balance password)
  (define (withdraw amount provided-password)
    (cond ((not (equal? password provided-password)) "bad password")
          ((< balance amount) "insufficient balance")
          (else (begin (set! balance (- balance amount))
                       balance))))
  withdraw)
