(define (make-account balance password)
  (define (dispatch meth . args)
    (cond ((eq? 'withdraw meth) (apply withdraw args))
          ((eq? 'add-account meth) (apply add-account! args))
          (#t (print "bad method"))))

  (define (add-account oldpass newpass)
    (if (member? oldpass )
        (set! password (cons newpass password))
        (print "bad password")))

  (define (withdraw amount provided-password)
    (cond ((not (member? provided-password password)) "bad password")
          ((< balance amount) "insufficient balance")
          (else (begin (set! balance (- balance amount))
                       balance))))
  (set! password (list password))
  dispatch)

(define (member? elt l)
  (cond ((null? l) #t)
        ((eq? elt (car l)) #t)
        (#t (member? elt (cdr l)))))
